import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Appbar from "@/components/Appbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-black" lang="en">
      <body className={inter.className}> <Appbar></Appbar>{children}</body>
    </html>
  );
}

