name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: Install dependencies
      run: npm ci
      working-directory: ./backend
      
    - name: Run Prisma generate
      run: npx prisma generate
      working-directory: ./backend
      
    - name: Build
      run: npm run build
      working-directory: ./backend

    - name: Start
      run: npm run start
      working-directory: ./backend
