name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json
      
    - name: Install dependencies
      run: npm ci
      working-directory: ./backend

    - name: Run installation script
      run: npm install
      working-directory: ./backend

    - name: Run Prisma generate
      run: npx prisma generate
      working-directory: ./backend/database

    - name: Create .env file
      run: |
        touch .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      working-directory: ./backend
      
    - name: Install PM2 globally
      run: npm install -g pm2
      
    - name: Start with PM2
      run: pm2 start dist/entrypoint.js --name "backend"
      working-directory: ./backend

    - name: Save PM2 process list
      run: pm2 save
